# Generated by Django 5.2.11 on 2026-03-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        ('quality_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality_match.product'),
        ),
        migrations.DeleteModel(
            name='QualityCheck',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
