# Generated by Django 5.2.11 on 2026-03-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
