# Generated by Django 5.2.11 on 2026-03-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_match', '0002_qualitycheck_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='grade',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
